# Generated by Django 4.2.1 on 2023-05-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=20)),
                ('book_price', models.IntegerField()),
                ('book_desc', models.CharField(max_length=100)),
            ],
        ),
    ]
