# Generated by Django 4.2.1 on 2023-05-23 05:45

import Booksapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Booksapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=Booksapp.models.upload_to)),
                ('book_one', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_one', to='Booksapp.books')),
                ('book_two', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_two', to='Booksapp.books')),
            ],
        ),
    ]
