# Generated by Django 4.2.1 on 2023-05-23 06:47

import Booksapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booksapp', '0003_alter_collection_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=Booksapp.models.upload_to),
        ),
    ]
